a = int(input("enter first number: "))
b = int(input("enter second number: "))
c = a+b
print("your sum is", c)


side = float(input("enter square sides:"))
area = side**2        # side^2
print("area of square is", area)

x = float(input("enter first float number:"))
y = float(input("enter second float number:"))
z = x+y

print("average of 2 float number is", z/2)


m = int(input("enter first number:"))
n = int(input("enter second number:"))

print(a >= b)
